require:
  - standard/cop/block_single_line_braces
  - rubocop-performance

inherit_gem:
  standard: config/base.yml

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false
