format = """\
    $username\
    $hostname\
    $directory\
    $git_branch\
    $git_state\
    $git_status\
    $nix_shell\
    $cmd_duration\
    $line_break\
    $jobs\
    $battery\
    $time\
    $character\
    """
