cask 'alfred'
cask 'bartender'
cask 'beardedspice'
cask 'brave-browser'
cask 'bettertouchtool'
cask 'cloudapp'
cask 'dash'
cask 'discord'
cask 'evernote'
cask 'firefox'
cask 'homebrew/cask-versions/firefox-developer-edition'
cask 'flux'
cask 'fork'
cask 'google-chrome'
cask 'handbrake'
cask 'istat-menus'
#cask 'ithoughtsx'
cask 'karabiner-elements'
cask 'loom'
#cask 'microsoft-excel' just use google docs
cask 'obs'
cask 'olive'
#cask 'onyx' causing issues right now
cask 'psequel'
cask 'sip'
cask 'skype'
cask 'slack'
cask 'spotify'
cask 'station'
cask 'tableplus'
cask 'telegram'
cask 'timing'
cask 'transmission'
cask 'visual-studio-code'
cask 'vlc'
cask 'zoom'
cask 'whatsapp'
cask 'xmind'
cask 'google-cloud-sdk'
cask 'docker'
cask 'google-backup-and-sync'
cask 'cleanshot'
cask 'netnewswire'
cask 'soulver'
cask 'soundsource'
cask 'qlmarkdown'
cask 'sigil'
cask 'gitup'
cask 'muzzle'
cask 'eloston-chromium' # ungoogled-chromium
cask 'imageoptim'
cask 'android-platform-tools' # adb
tap 'melonamin/formulae'
cask 'swiftbar'
tap 'homebrew/cask-fonts'
cask 'font-fira-code'
cask 'font-fira-code-nerd-font'
cask 'font-hack-nerd-font'
cask 'font-inter'
cask 'font-cascadia'
cask 'meetingbar'

brew 'ffmpeg'
brew 'fish'
brew 'git'
brew 'go'
brew 'node'
brew 'python'
brew 'rust'
brew 'postgresql'
brew 'wget'
brew 'youtube-dl'
brew 'zsh'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'
brew 'zsh-autosuggestions'
brew 'mas'
brew 'chruby'
brew 'ruby-install'
brew 'apply-user-defaults'
brew 'stow'
brew 'cfssl'
brew 're2'
brew 'fzf'
brew 'ripgrep'
brew 'starship'
brew 'yarn'
brew 'lsd'
brew 'bat'
brew 'fd'
brew 'procs'
brew 'sd'
brew 'dust'
brew 'zoxide'
brew 'switchaudio-osx'
brew 'vips'
brew 'tealdeer'
brew 'bandwhich'
brew 'grex'
brew 'avr-gcc'
brew 'bitwarden-cli'

tap 'federico-terzi/espanso'
brew 'espanso'
tap 'zero-sh/tap'
brew 'zero'
brew 'apply-user-defaults'
tap 'khanhas/tap'
brew 'spicetify-cli'
tap 'yqrashawn/goku'
brew 'goku'
tap 'Schniz/tap'
brew 'fnm'
tap 'cjbassi/ytop'
brew 'ytop'
tap 'shopify/shopify'
brew 'themekit'
tap 'heroku/brew'
brew 'heroku'
tap ' qmk/qmk'
brew 'qmk'

mas 'Todoist', id: 585829637
mas 'Day One', id: 1055511498
mas 'Meeter for Zoom, Teams & Co', id: 1510445899
mas 'iA Writer', id: 775737590
mas 'WireGuard', id: 1451685025
mas 'Harvest', id: 506189836
