# espanso configuration file
# https://espanso.org/docs/

matches:
  - trigger: "..e"
    replace: "w@waynehoover.com"

  - trigger: "..l"
    replace: "[$|$](https://)"

  - trigger: "i'm"
    replace: "I'm"

  - trigger: "i'll"
    replace: "I'll"

  - triggers: ["teh", "thee"]
    replace: "the"
    word: true

  - trigger: "dont"
    replace: "don't"
    word: true

  - trigger: "cant"
    replace: "can't"
    word: true

  - trigger: "consc"
    replace: "consciousness"
    word: true

  - trigger: "..p"
    replace: ":phoenix:"

  - trigger: "..d"
    replace: |
            [[Daily Journal]]
            3 Things grateful for
            3 Things that would make today great
            5 Priorities of the day

  - trigger: "<a.."
    replace: "<a href='{{clipboard}}' />$|$</a>"
    vars:
      - name: "clipboard"
        type: "clipboard"

toggle_key: OFF

